name: Deploy Assessment Timetables

on:
  schedule:
    - cron: '37 1 * * *'
  push:
    branches: ["main"]
    paths:
      - "**"
      - ".github/workflows/deploy-timetables.yml"

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: |
          npm ci

      - name: Build Year 10
        env:
          VITE_APP_TITLE: "Year 10 Assessment Calendar"
        run: |
          # Read SHEET_URL from file
          export SHEET_URL=$(cat scripts/year-10-sheet-url.txt)
          # Generate Data
          node scripts/download-and-parse.js
          # Build with Base URL - including repo name
          npm run build -- --base=/bassaleg-assessment-calendar/year-10/
          # Move to artifacts
          mkdir -p build_artifacts/year-10
          cp -r dist/* build_artifacts/year-10/

      - name: Build Year 11
        env:
          VITE_APP_TITLE: "Year 11 Assessment Calendar"
        run: |
          # Read SHEET_URL from file
          export SHEET_URL=$(cat scripts/year-11-sheet-url.txt)
          # Generate Data
          node scripts/download-and-parse.js
          # Build with Base URL - including repo name
          npm run build -- --base=/bassaleg-assessment-calendar/year-11/
          # Move to artifacts
          mkdir -p build_artifacts/year-11
          cp -r dist/* build_artifacts/year-11/

      - name: Create Landing Page
        run: |
          cp .github/workflows/landing-page.html build_artifacts/index.html

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build_artifacts
          branch: gh-pages